name: Build sysbox

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: {}
  workflow_run:
    workflows:
      - Build base sysbox
    types:
      - completed

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "0.8.9"

      - uses: actions/checkout@v4
      
      - name: Build sysbox
        run: |
          earthly --ci --use-inline-cache --save-inline-cache --push +sysbox --registry ${{ env.REGISTRY }}/${{ github.repository_owner }}
